# Generated by Django 3.0.2 on 2020-09-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200922_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'about'},
        ),
    ]
