# Generated by Django 3.0.2 on 2020-09-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200922_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': ''},
        ),
    ]
